# region         = "eu-west-1"
# profile        = "default"
# environment    = "staging"
# ami            = "ami-0a1b36900d715a3ad"
# instance_type  = "t2.micro"
# key_name       = "altcloud_ssh"
# key_filename   = "/Users/sibyl/.ssh/altcloud_ssh.pub"
# security_group = "altcloud_sg"
